name: CI - Run ETL Tests
on:
  push:
    branches: [main]

jobs:
  test:
    run-on: ubuntu-latest

    steps:
      - name: Checkout your code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pytest testetl.py
      